import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {ngGameplanStudyControls} from '../neural/src/game-study-controls.src.js';
// Small event/DOM host, not a browser/layout claim. No external DOM package required.
class Element {
 constructor(tag,doc){this.tagName=tag;this.ownerDocument=doc;this.children=[];this.attrs={};this.style={};this.listeners={};this.disabled=false;this.value='';this._text='';}
 set textContent(v){this._text=String(v);this.children=[];} get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}
 set innerHTML(_){throw Error('HTML sink forbidden');}
 appendChild(c){if(c.parent)c.parent.children=c.parent.children.filter(x=>x!==c);this.children.push(c);c.parent=this;return c;}
 replaceChildren(...children){for(const c of this.children)c.parent=null;this.children=[];this._text='';children.forEach(c=>this.appendChild(c));}
 setAttribute(k,v){this.attrs[k]=String(v);} getAttribute(k){return this.attrs[k]??null;}
 addEventListener(k,f){this.listeners[k]=f;} dispatch(type){if(type==='click'&&this.disabled)return;this.listeners[type]?.({target:this});}
 focus(){this.ownerDocument.activeElement=this;} contains(el){return this===el||this.children.some(c=>c.contains(el));}
}
const document=()=>{const d={activeElement:null,createElement:tag=>new Element(tag,d)};return d;};
const all=root=>[root,...root.children.flatMap(all)];const control=(root,name)=>all(root).find(x=>x.getAttribute('data-study-control')===name);
const keyButton=(root,key,action='select')=>all(root).find(x=>x.getAttribute('data-study-key')===key&&x.getAttribute('data-study-action')===action);
const source=readFileSync(new URL('../neural/src/app.src.jsx',import.meta.url),'utf8');
function method(name){const m=new RegExp('^  (?:async )?'+name+'\\([^\\n]*\\) \\{','m').exec(source);assert.ok(m,name);const tail=source.slice(m.index),next=/\n  (?:async )?[A-Za-z_$][\w$]*\([^\n]*\) \{/.exec(tail.slice(1));return next?tail.slice(0,next.index+1):tail;}
const methods=['nodeForKey','posFamily','_cardsOf','_deckCardCount','giAllows','_rebuildRulesetMask','_rulesetMask','rsAllowsIdx','startFrom'];
const App=Function('return class {\n'+methods.map(method).join('\n')+'\n}')();
function fixture(extra=0){const app=new App(),doc=document();Object.assign(app,{_progressOwnerStamp:'guest',_progressLoaded:true,_progressCurrent:()=>true,_giMode:'gi',_hydrateGiMode(){return this._giMode;},get(k,fallback){return this.settings[k]??fallback;},settings:{},_decision:{},maxMoves:12,aiSkill:.07,nodes:[],flashcards:{decks:{}},events:[],_session:{keys:['keep2','keep1'],idx:1},srs:{keep:1},rng(){throw Error('no RNG');},flowScore(){this.events.push('flow');},_gameStudyChanged(reason){this.events.push('changed:'+reason);},_requestGameplanStudy(intent){this.events.push('request:'+intent);return Promise.resolve();},deckKeyFor(n){return {key:n.key};}});
 const position={idx:0,id:'P',ty:'positions',t:'Mount',cal:{avail:{gi:true,nogi:true}}};const gi={idx:1,id:'G',ty:'positions',t:'Gi Guard',cal:{avail:{gi:true,nogi:false}}};app.nodes.push(position,gi);
 for(const key of ['Mount|Top','Mount|Bottom','Gi Guard|Top','Gi Guard|Bottom'])app.flashcards.decks[key]={n:3};
 for(const key of ['Move|Attacker','Move|Defender']){app.nodes.push({idx:app.nodes.length,id:key,ty:'transitions',key,cal:{avail:{gi:true,nogi:true}}});app.flashcards.decks[key]={cards:[{},{}]};}
 for(let i=0;i<extra;i++){const key='Z'+String(i).padStart(2,'0')+'|Attacker';app.nodes.push({idx:app.nodes.length,id:key,ty:'transitions',key,cal:{avail:{gi:true,nogi:true}}});app.flashcards.decks[key]={n:1};}
 return {app,doc,root:ngGameplanStudyControls(app,{document:doc})};}
const scope=(f,value)=>{const x=control(f.root,'scope');x.value=value;x.dispatch('change');};
const search=(f,value)=>{const x=control(f.root,'search');x.value=value;x.dispatch('input');};
const settle=()=>new Promise(r=>setImmediate(r));
test('no default scope, selection, fetch, ranking or study intent on mount and edits',()=>{const f=fixture();assert.equal(control(f.root,'scope').value,'');assert.equal(control(f.root,'compare').disabled,true);search(f,'Mount');keyButton(f.root,'Mount|Top').dispatch('click');scope(f,'current-position');assert.deepEqual(f.app.events,[]);assert.equal(f.app._gameplanStudyDeclaration,undefined);assert.equal(f.app._keyNode,undefined);assert.equal(f.app._rsOk,undefined);});
test('actual app readers retain exact Top Bottom Attacker Defender deck keys',()=>{const f=fixture();for(const key of ['Mount|Top','Mount|Bottom','Move|Attacker','Move|Defender'])assert.equal(keyButton(f.root,key).disabled,false);});
test('no-gi eligibility uses actual producer availability and selected inactive deck stays removable',()=>{const f=fixture();keyButton(f.root,'Gi Guard|Top').dispatch('click');scope(f,'current-position');f.app._giMode='nogi';assert.equal(ngGameplanStudyControls(f.app,{document:f.doc}),f.root);assert.equal(keyButton(f.root,'Gi Guard|Top').disabled,true);assert.ok(keyButton(f.root,'Gi Guard|Top','remove'));assert.equal(control(f.root,'compare').disabled,true);keyButton(f.root,'Gi Guard|Top','remove').dispatch('click');assert.match(control(f.root,'selected').textContent,/No techniques selected/);});
test('Compare dispatches copied sharp-only declaration with exact roles and in order',async()=>{const f=fixture();scope(f,'current-position');keyButton(f.root,'Mount|Bottom').dispatch('click');keyButton(f.root,'Move|Defender').dispatch('click');control(f.root,'compare').dispatch('click');await settle();assert.deepEqual(f.app._gameplanStudyDeclaration,{mode:'current-position',targets:{kind:'sharp-refresh',deckKeys:['Mount|Bottom','Move|Defender']}});assert.deepEqual(f.app.events,['changed:declaration','request:suggestions']);keyButton(f.root,'Mount|Bottom','remove').dispatch('click');assert.equal(f.app._gameplanStudyDeclaration.targets.deckKeys.length,2);});
test('FLOW prepares only on explicit next-roll weak Compare',async()=>{const f=fixture();f.app.settings.startFrom='weak';scope(f,'next-roll-current-conditions');keyButton(f.root,'Mount|Top').dispatch('click');assert.deepEqual(f.app.events,[]);control(f.root,'compare').dispatch('click');await settle();assert.deepEqual(f.app.events,['flow','changed:declaration','request:suggestions']);assert.match(f.root.textContent,/keeping this roll’s length and opponent strength the same/);});
test('current-position weak selection and next-roll random never prepare FLOW',async()=>{for(const mode of ['current-position','next-roll-current-conditions']){const f=fixture();f.app.settings.startFrom=mode==='current-position'?'weak':'random';scope(f,mode);keyButton(f.root,'Mount|Top').dispatch('click');control(f.root,'compare').dispatch('click');await settle();assert.ok(!f.app.events.includes('flow'));}});
test('manifest removal between paint and Compare prevents dispatch and retains stale selection',()=>{const f=fixture();scope(f,'current-position');keyButton(f.root,'Mount|Top').dispatch('click');delete f.app.flashcards.decks['Mount|Top'];control(f.root,'compare').dispatch('click');assert.deepEqual(f.app.events,[]);assert.match(control(f.root,'selected').textContent,/No longer available/);assert.ok(keyButton(f.root,'Mount|Top','remove'));});
test('explicit pagination exposes all matches with counts and never truncates selected draft',()=>{const f=fixture(21);assert.match(control(f.root,'count').textContent,/27 of 27/);assert.match(control(f.root,'count').textContent,/Showing 1–12/);control(f.root,'next').dispatch('click');assert.match(control(f.root,'count').textContent,/Showing 13–24/);control(f.root,'next').dispatch('click');assert.match(control(f.root,'count').textContent,/Showing 25–27/);assert.equal(control(f.root,'next').disabled,true);search(f,'Z20');keyButton(f.root,'Z20|Attacker').dispatch('click');search(f,'Mount');assert.ok(keyButton(f.root,'Z20|Attacker','remove'));assert.deepEqual(f.app.events,[]);});
test('repaint reuses element draft search focus and active review queue order',()=>{const f=fixture(),queue=f.app._session,keys=queue.keys;search(f,'Mount');scope(f,'current-position');keyButton(f.root,'Mount|Top').dispatch('click');control(f.root,'search').focus();const root=ngGameplanStudyControls(f.app,{document:f.doc});assert.equal(root,f.root);assert.equal(control(root,'search').value,'Mount');assert.equal(f.doc.activeElement,control(root,'search'));assert.equal(f.app._session,queue);assert.equal(f.app._session.keys,keys);assert.deepEqual(keys,['keep2','keep1']);assert.equal(queue.idx,1);});
test('owner change starts blank and stale prior-owner Compare cannot dispatch',()=>{const f=fixture();scope(f,'current-position');keyButton(f.root,'Mount|Top').dispatch('click');const old=f.root;f.app._progressOwnerStamp='account:B';const fresh=ngGameplanStudyControls(f.app,{document:f.doc});assert.notEqual(fresh,old);assert.equal(control(fresh,'scope').value,'');control(old,'compare').dispatch('click');assert.deepEqual(f.app.events,[]);});
test('unavailable current decision and unsupported role or empty deck remain explicit',()=>{const f=fixture();f.app._decision=null;f.app.flashcards.decks['Bad|Coach']={n:2};f.app.flashcards.decks['Mount|Top']={n:0};ngGameplanStudyControls(f.app,{document:f.doc});scope(f,'current-position');assert.equal(keyButton(f.root,'Bad|Coach').disabled,true);assert.equal(keyButton(f.root,'Mount|Top').disabled,true);assert.match(control(f.root,'message').textContent,/Choose a move/);});
test('all controls are one-column 44px text-only and hostile deck text stays text',()=>{const f=fixture();const key='<img onerror=boom>|Attacker';f.app.flashcards.decks[key]={n:1};f.app.nodes.push({idx:f.app.nodes.length,id:'hostile',key,ty:'transitions'});ngGameplanStudyControls(f.app,{document:f.doc});assert.match(f.root.style.cssText,/grid-template-columns:minmax\(0,1fr\)/);for(const el of all(f.root).filter(x=>['button','input','select'].includes(x.tagName)))assert.match(el.style.cssText,/min-height:44px/);assert.ok(keyButton(f.root,key).textContent.includes('<img'));});
test('pending comparison coalesces double click and leaves external review focus untouched on repaint',async()=>{const f=fixture();let release;f.app._requestGameplanStudy=intent=>{f.app.events.push('request:'+intent);return new Promise(r=>release=r);};scope(f,'current-position');keyButton(f.root,'Mount|Top').dispatch('click');const external=f.doc.createElement('button');external.focus();control(f.root,'compare').dispatch('click');control(f.root,'compare').dispatch('click');ngGameplanStudyControls(f.app,{document:f.doc});assert.equal(f.doc.activeElement,external);assert.equal(f.app.events.filter(x=>x.startsWith('request:')).length,1);release();await settle();assert.equal(control(f.root,'compare').disabled,false);});
test('source expiry before Compare cannot use stale playable state',()=>{const f=fixture();scope(f,'current-position');keyButton(f.root,'Gi Guard|Top').dispatch('click');f.app._giMode='nogi';control(f.root,'compare').dispatch('click');assert.deepEqual(f.app.events,[]);assert.match(control(f.root,'message').textContent,/Remove unavailable/);});
test('missing service is explicit and does not replace declaration',()=>{const f=fixture();scope(f,'current-position');keyButton(f.root,'Mount|Top').dispatch('click');f.app._requestGameplanStudy=null;control(f.root,'compare').dispatch('click');assert.equal(f.app._gameplanStudyDeclaration,undefined);assert.match(control(f.root,'message').textContent,/service is unavailable/);});
test('eligibility matches producer giAllows including playable-mask alias difference',()=>{const f=fixture();f.app.nodes[0].cal.stateAlias='Some canonical node';assert.equal(f.app.rsAllowsIdx(0),false);assert.equal(f.app.giAllows(f.app.nodes[0]),true);ngGameplanStudyControls(f.app,{document:f.doc});assert.equal(keyButton(f.root,'Mount|Top').disabled,false);assert.equal(keyButton(f.root,'Mount|Bottom').disabled,false);f.app.nodes[0].cal.avail.gi=false;ngGameplanStudyControls(f.app,{document:f.doc});assert.equal(keyButton(f.root,'Mount|Top').disabled,true);});
test('player copy uses technique role labels and percentages while retaining exact declaration keys',async()=>{const f=fixture();scope(f,'current-position');const choose=keyButton(f.root,'Mount|Bottom');assert.equal(choose.textContent,'Select: Mount · Bottom');choose.dispatch('click');assert.match(control(f.root,'selected').textContent,/Mount · Bottom/);assert.match(f.root.textContent,/10% sharpness bonus/);assert.match(f.root.textContent,/simulated win chance/);assert.doesNotMatch(f.root.textContent,/manifest|input producer|hypothetical|0\.10|source eligibility|\|/i);control(f.root,'compare').dispatch('click');await settle();assert.deepEqual(f.app._gameplanStudyDeclaration.targets.deckKeys,['Mount|Bottom']);});
test('an external repaint that changes nothing keeps the very same row buttons; a real change rebuilds them',()=>{
 // The app repaints this panel whenever study priority moves, including every Win-chance paint. A
 // rebuilt-but-identical row swapped a button out between pointerdown and pointerup and lost the
 // click (v1.207.8). Mutant, recorded 2026-09-29: rebuilding unconditionally turns the identity half red.
 const f=fixture();search(f,'Mount');const before=keyButton(f.root,'Mount|Top');
 assert.equal(ngGameplanStudyControls(f.app,{document:f.doc}),f.root);
 assert.equal(keyButton(f.root,'Mount|Top'),before,'an unchanged repaint keeps the same button object');
 before.dispatch('click');const after=keyButton(f.root,'Mount|Top');
 assert.notEqual(after,before,'selecting changes the row, so it is rebuilt');assert.equal(after.textContent,'Selected: Mount · Top');
 delete f.app.flashcards.decks['Mount|Top'];ngGameplanStudyControls(f.app,{document:f.doc});
 assert.match(control(f.root,'selected').textContent,/No longer available/,'a manifest change still reaches the rows');
});
