import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash, webcrypto } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { ngSystemsCreateLoader } from '../neural/src/systems-demand.src.js';
const bytes = v => new TextEncoder().encode(JSON.stringify(v));
const full = id => ({id,name:id,display_title:id,aliases:['alias'],type:'Guard',difficulty:'Intermediate',nodes:['node'],glue:[{nodes:['node']}],products:[{name:'Course',instructor:'Teacher',url:'unchanged'}]});
function fixture() {
 const a=full('Systems/A'), b=full('Systems/B'), bodies=new Map(), rows=[a,b].map(s=>{const data=bytes(s),detailHash=createHash('sha256').update(data).digest('hex');bodies.set('content/system-records/'+detailHash+'.json',data);return {id:s.id,name:s.name,display_title:s.display_title,aliases:s.aliases,type:s.type,difficulty:s.difficulty,products:s.products.map(({name,instructor})=>({name,instructor})),detailHash};});
 const index={version:1,_meta:{count:2},systems:rows};bodies.set('systems-index.json',bytes(index));const calls=[];
 const fetch=async (url,options)=>{calls.push(url); const data=bodies.get(url);return {ok:!!data,arrayBuffer:async()=>data};};
 return {a,b,index,bodies,calls,fetch,loader:ngSystemsCreateLoader({fetch,crypto:webcrypto})};
}
test('construction does not fetch',()=>{assert.equal(fixture().calls.length,0);});
test('index preserves complete search fields without loading records',async()=>{const f=fixture();assert.deepEqual(await f.loader.index(),f.index);assert.deepEqual(f.calls,['systems-index.json']);});
test('one selection fetches exactly one immutable record and preserves full data',async()=>{const f=fixture();assert.deepEqual(await f.loader.record(f.a.id),f.a);assert.equal(f.calls.length,2);assert.match(f.calls[1],/^content\/system-records\/[a-f0-9]{64}\.json$/);});
test('parallel selection coalesces and subsequent lookup reuses record',async()=>{const f=fixture();await Promise.all([f.loader.record(f.a.id),f.loader.record(f.a.id)]);await f.loader.record(f.a.id);assert.equal(f.calls.length,2);});
test('hash mismatch refuses altered product or roster',async()=>{const f=fixture();f.bodies.set('content/system-records/'+f.index.systems[0].detailHash+'.json',bytes({...f.a,nodes:[]}));await assert.rejects(f.loader.record(f.a.id),/systems-record-hash/);});
test('failed record needs explicit retry and then recovers',async()=>{const f=fixture();const key='content/system-records/'+f.index.systems[0].detailHash+'.json', original=f.bodies.get(key);f.bodies.delete(key);await assert.rejects(f.loader.record(f.a.id));f.bodies.set(key,original);await assert.rejects(f.loader.record(f.a.id));assert.deepEqual(await f.loader.record(f.a.id,{retry:true}),f.a);assert.equal(f.calls.length,4);});
test('failed index explicitly retries',async()=>{const f=fixture();const b=f.bodies.get('systems-index.json');f.bodies.delete('systems-index.json');await assert.rejects(f.loader.index());f.bodies.set('systems-index.json',b);await assert.rejects(f.loader.index());assert.deepEqual(await f.loader.index({retry:true}),f.index);});
test('unknown ID never fetches a record',async()=>{const f=fixture();await assert.rejects(f.loader.record('Systems/unknown'),/systems-unknown-id/);assert.equal(f.calls.length,1);});
test('duplicate index ID rejected',async()=>{const f=fixture();f.index.systems.push(f.index.systems[0]);f.bodies.set('systems-index.json',bytes(f.index));await assert.rejects(f.loader.index(),/systems-index-row/);});
test('record index disagreement refused even with valid record hash',async()=>{const f=fixture();f.index.systems[0].name='Wrong';f.bodies.set('systems-index.json',bytes(f.index));await assert.rejects(f.loader.record(f.a.id),/systems-record-index/);});
test('dispose refuses a late fetch that ignores abort',async()=>{let release;const f=fixture(),l=ngSystemsCreateLoader({crypto:webcrypto,fetch:()=>new Promise(resolve=>release=resolve)});const pending=l.index();l.dispose();release({ok:true,arrayBuffer:async()=>bytes(f.index)});await assert.rejects(pending,/systems-disposed/);assert.throws(()=>l.index(),/systems-disposed/);});
const appSource=readFileSync(new URL('../neural/src/app.src.jsx',import.meta.url),'utf8');
function method(name){const re=new RegExp('^  (?:async )?'+name+'\\([^\\n]*\\) \\{','m'),m=re.exec(appSource);assert.ok(m,name);const tail=appSource.slice(m.index),next=/\n  (?:async )?[A-Za-z_$][\w$]*\([^\n]*\) \{/.exec(tail.slice(1));return next?tail.slice(0,next.index+1):tail;}
const names=['_ensureSystems','_systemReady','_ensureSystemRecord','_deferSystemBucket','openSystem'];
const App=Function('ngSystemsCreateLoader','return class {\n'+names.map(method).join('\n')+'\n}')(ngSystemsCreateLoader);
function app(){const a=new App();Object.assign(a,{deckShown:true,_viewMode:'explore',explorerSearchRef:{current:null},explorerListRef:{current:null},paints:[],_leaveRollForReference(){},clearFocus(){this._systemIntent=(this._systemIntent||0)+1;this._systemId=null;},_pushUrl(){},showExplorerList(){this.paints.push(this._systemId+':'+this._systemRecordStatus);},_systemBody(){},track(){},setFocusIdxSet(x){this.focus=x;},systemNodeIdxs(){return [1];}});return a;}
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve};};
test('actual openSystem paints pending, then selected ready roster',async()=>{const a=app(),d=deferred();a._ensureSystemRecord=()=>d.promise;const p=a.openSystem('Systems/A');assert.equal(a._systemRecordStatus,'pending');assert.equal(a.focus,undefined);d.resolve(full('Systems/A'));await p;assert.equal(a._systemRecordStatus,'ready');assert.deepEqual(a.focus,[1]);});
test('actual A-to-B ignores late A completion',async()=>{const a=app(),da=deferred(),db=deferred();a._ensureSystemRecord=id=>id.endsWith('A')?da.promise:db.promise;const pa=a.openSystem('Systems/A'),pb=a.openSystem('Systems/B');db.resolve(full('Systems/B'));await pb;const before=a.paints.slice();da.resolve(full('Systems/A'));assert.equal(await pa,null);assert.deepEqual(a.paints,before);});
test('actual close or unmount prevents late paint',async()=>{for(const destroy of [false,true]){const a=app(),d=deferred();a._ensureSystemRecord=()=>d.promise;const p=a.openSystem('Systems/A');if(destroy)a.__ngDestroyed=true;else a.clearFocus();const before=a.paints.slice();d.resolve(full('Systems/A'));assert.equal(await p,null);assert.deepEqual(a.paints,before);}});
test('actual unavailable record remains error, never empty ready roster',async()=>{const a=app();a._ensureSystemRecord=async()=>null;assert.equal(await a.openSystem('Systems/A'),null);assert.equal(a._systemRecordStatus,'error');assert.equal(a.focus,undefined);});
test('actual bucket resumes only after a ready selected record',async()=>{const a=app(),d=deferred();let resumed=0;a._ensureSystemRecord=()=>d.promise;assert.equal(a._deferSystemBucket('system:Systems/A',()=>resumed++),true);assert.equal(resumed,0);d.resolve(full('Systems/A'));await new Promise(r=>setImmediate(r));assert.equal(resumed,1);});
test('actual superseded bucket never starts a stale session',async()=>{const a=app(),da=deferred(),db=deferred();let resumed=0;a._ensureSystemRecord=id=>id.endsWith('A')?da.promise:db.promise;a._deferSystemBucket('system:Systems/A',()=>resumed++);const p=a.openSystem('Systems/B');db.resolve(full('Systems/B'));await p;da.resolve(full('Systems/A'));await new Promise(r=>setImmediate(r));assert.equal(resumed,0);});
test('explicit retry does not duplicate pending index or record requests',async()=>{const f=fixture();await Promise.all([f.loader.index(),f.loader.index({retry:true})]);await Promise.all([f.loader.record(f.a.id,{retry:true}),f.loader.record(f.a.id,{retry:true})]);assert.equal(f.calls.length,3);});
test('actual hydration resolves case-insensitive direct route and keeps exact record fields',async()=>{const a=app(),f=fixture();a._ensureSystems=async()=>{};a._systemsById=Object.fromEntries(f.index.systems.map(s=>[s.id,s]));a.systems=f.index.systems;a._systemsLoader=f.loader;assert.deepEqual(await a._ensureSystemRecord('systems/a'),f.a);assert.deepEqual(a._systemsById[f.a.id],f.a);assert.equal(a.systems[0].detailHash,undefined);});
test('actual hydration after unmount does not alter app catalogue',async()=>{const a=app(),f=fixture(),d=deferred();a._ensureSystems=async()=>{};a.systems=f.index.systems;a._systemsById=Object.fromEntries(a.systems.map(s=>[s.id,s]));a._systemsLoader={record:()=>d.promise};const p=a._ensureSystemRecord(f.a.id);await Promise.resolve();a.__ngDestroyed=true;d.resolve(f.a);assert.equal(await p,null);assert.ok(a._systemsById[f.a.id].detailHash);});
test('actual system bucket keeps authored glue ordering and ruleset filter',()=>{const Bucket=Function('return class {\n'+method('bucketTechniques')+'\n} ')();const a=new Bucket();const s=full('Systems/A');s.nodes=['z','x'];s.glue=[{nodes:['x','z','x']}];Object.assign(a,{systems:[s],_systemReady:s=>!!s&&!s.detailHash,flashcards:{decks:{X:{},Z:{}}},_idIndex:new Map([['x',0],['z',1]]),nodes:[{key:'X'},{key:'Z'}],rsAllows:n=>n.key==='X',deckKeyFor:n=>({key:n.key})});assert.deepEqual(a.bucketTechniques('system:Systems/A'),['X']);a.rsAllows=()=>true;assert.deepEqual(a.bucketTechniques('system:Systems/A'),['X','Z']);});
test('actual direct Systems route reserves reference intent before index completion',()=>{const Route=Function('return class {\n'+method('_seedPageFromUrl')+'\n'+method('_decodePath')+'\n'+method('_urlFault')+'\n}')();const a=new Route(),calls=[];a.openSystem=id=>calls.push(id);assert.equal(a._seedPageFromUrl('/Systems/A'),false);assert.equal(a._refPage,true);assert.deepEqual(calls,['Systems/A']);});
test('actual explicit retry forwards retry and recovers selected record',async()=>{const a=app(),flags=[];a._ensureSystemRecord=async(id,retry)=>{flags.push(retry);return retry?full(id):null;};await a.openSystem('Systems/A');assert.equal(a._systemRecordStatus,'error');await a.openSystem('Systems/A',true);assert.deepEqual(flags,[false,true]);assert.equal(a._systemRecordStatus,'ready');});
test('actual failed bucket retry resumes the original bucket once',async()=>{const a=app();let resumed=0;a._ensureSystemRecord=async(id,retry)=>retry?full(id):null;a._deferSystemBucket('system:Systems/A',()=>resumed++);await new Promise(r=>setImmediate(r));assert.equal(a._systemRecordStatus,'error');a._systemRetryBucket.run();await new Promise(r=>setImmediate(r));assert.equal(resumed,1);});
function releases(){const old=fixture(),fresh=fixture();fresh.a.nodes=['new'];const body=bytes(fresh.a),hash=createHash('sha256').update(body).digest('hex');fresh.index.systems[0].detailHash=hash;fresh.bodies.set('systems-index.json',bytes(fresh.index));fresh.bodies.set('content/system-records/'+hash+'.json',body);fresh.bodies.delete('content/system-records/'+old.index.systems[0].detailHash+'.json');return {old,fresh};}
test('cached index A recovers missing old hash with one explicit fresh index B and selected record',async()=>{const {old,fresh}=releases(),calls=[];let active=old;const loader=ngSystemsCreateLoader({crypto:webcrypto,fetch:async(path,options)=>{calls.push({path,cache:options.cache});return active.fetch(path,options);}});await loader.index();active=fresh;await assert.rejects(loader.record(old.a.id),/systems-http/);assert.deepEqual(await loader.record(old.a.id,{retry:true}),fresh.a);assert.equal(calls.filter(x=>x.path==='systems-index.json').length,2);assert.equal(calls.at(-2).cache,'reload');assert.equal(calls.at(-1).cache,'reload');assert.equal(calls.length,4);});
test('successful index refresh really changes generation; late A body cannot become ready under B',async()=>{const {old,fresh}=releases(),d=deferred();let active=old,block=true;const loader=ngSystemsCreateLoader({crypto:webcrypto,fetch:async(path,options)=>path.includes('system-records')&&block?d.promise:active.fetch(path,options)});await loader.index();const pending=loader.record(old.a.id);await new Promise(r=>setImmediate(r));active=fresh;block=false;await loader.index({retry:true});d.resolve({ok:true,arrayBuffer:async()=>bytes(old.a)});await assert.rejects(pending,/systems-stale-generation/);assert.deepEqual(await loader.record(old.a.id),fresh.a);});
test('refresh with removed selected ID refuses without fetching another record',async()=>{const {old,fresh}=releases();let active=old;const loader=ngSystemsCreateLoader({crypto:webcrypto,fetch:(...args)=>active.fetch(...args)});await loader.index();fresh.index.systems=fresh.index.systems.filter(r=>r.id!==old.a.id);fresh.bodies.set('systems-index.json',bytes(fresh.index));active=fresh;await assert.rejects(loader.record(old.a.id,{retry:true}),/systems-unknown-id/);assert.deepEqual(fresh.calls,['systems-index.json']);});
test('actual chrome owns pending unknown and lowercase System details',()=>{const Detail=Function('return class {\n'+method('_exploreDetailOwnsList')+'\n}')();for(const id of ['Systems/A','systems/a','Systems/Unknown']){const a=new Detail();a._systemId=id;assert.equal(a._exploreDetailOwnsList(),true);a._exQ='query';assert.equal(a._exploreDetailOwnsList(),false);}});
test('actual body callback never paints a destroyed instance',()=>{const Detail=Function('return class {\n'+method('_systemBody')+'\n}')();const a=new Detail();let landed,paints=0;Object.assign(a,{_systemId:'Systems/A',deckShown:true,_viewMode:'explore',_docBody:(_k,fn)=>{landed=fn;return null;},renderExplorer:()=>paints++});a._systemBody({id:'Systems/A',key:'A|System'});a.__ngDestroyed=true;landed();assert.equal(paints,0);});
test('actual app retry refreshes catalogue once and re-resolves same selected system',async()=>{const {old,fresh}=releases();let active=old;const a=app();a._systemsLoader=ngSystemsCreateLoader({crypto:webcrypto,fetch:(...args)=>active.fetch(...args)});a._dataBase=()=>'';a._ensureReferenceCSS=()=>{};a._renderPaneBody=()=>{};a._onSystems=function(){this._systemsById=Object.fromEntries(this.systems.map(s=>[s.id,s]));};await a._ensureSystems();active=fresh;assert.equal(await a.openSystem(old.a.id),null);assert.deepEqual(await a.openSystem(old.a.id,true),fresh.a);assert.deepEqual(a._systemsById[fresh.a.id].nodes,['new']);assert.equal(fresh.calls.filter(x=>x==='systems-index.json').length,1);});
test('browser fixture uses production wire hashes and only the selected record endpoint',async()=>{const {systemsDemandFixture,routeSystemsDemand}=await import('../e2e/journeys/systems-demand-fixture.ts');const f=fixture(), wire=systemsDemandFixture({_meta:{count:2},systems:[f.a,f.b]}), routes=[];await routeSystemsDemand({route:async(pattern,handler)=>routes.push({pattern,handler})},{systems:[f.a,f.b]});assert.equal(routes.length,2);const loader=ngSystemsCreateLoader({crypto:webcrypto,fetch:async path=>{if(path==='systems-index.json')return {ok:true,arrayBuffer:async()=>bytes(wire.index)};const hash=path.split('/').pop().replace(/\.json$/,'');const value=wire.records.get(hash);return {ok:!!value,arrayBuffer:async()=>new TextEncoder().encode(value)};}});assert.deepEqual(await loader.record(f.a.id),f.a);});
