import { test, expect } from '@playwright/test'
import { journey } from '../dsl'

// Mutation coverage: shared fixed-red threat palette and hidden threat odds fail the first journey.
// An initial-render-only red override survives because the live refresh restores the score color.
// THREAT CARDS PRINT WIN CHANCE (v1.207.0, owner 2026-09-29): your win chance if they try that move.
// While you apply a submission their moves are their escapes, valued by the engine's escape probes
// (v1.207.6). Mutant, recorded 2026-09-29: requesting no probes on a submission (the v1.207.2 rule)
// turns the first journey red on its poll ("—" forever). While you DEFEND, the finish card is the
// decision you are in and prints V(s), the legend's number (it printed EDGE's -100 before v1.207.0).

test('@curated submission choices distinguish switching attacks, finishing, and opponent threats', async ({page})=>{
  const errors:string[]=[]; page.on('pageerror', e=>errors.push(e.message))
  const j=journey(page)
  await j.boot('/Submissions/Triangle-Choke/from-Triangle-Control/Attacker')
  await j.advance(4000)
  const own=page.locator('[data-choice-group="you"]')
  await expect(own.locator('[data-choice-action="finish"]')).toHaveCount(1)
  await expect(own).toContainText('Attack Kimura')
  await expect(own).toContainText('Attack Americana')
  await expect(own).toContainText('Attack straight arm lock')
  await expect(own).toContainText('Take the back')
  const threats=page.locator('[data-choice-group="opponent"] [data-opponent-threat]')
  await expect(threats.locator('.ngodds')).toHaveCount(2)
  await expect(threats.first().locator('.ngbotrow > div')).toHaveText('Odds')
  await expect.poll(()=>threats.locator('[data-threat-win]').allTextContents(),{timeout:45_000}).toEqual([expect.stringMatching(/%$/),expect.stringMatching(/%$/)])
  const marks=await threats.evaluateAll(cards=>cards.map(card=>({points:card.querySelector('.ngedge')?.textContent,color:(card.querySelector('.ngbar') as HTMLElement).style.background,odds:card.querySelector('.ngodds')?.textContent})))
  expect(marks[0].points).not.toBe(marks[1].points)
  expect(marks[0].color).not.toBe(marks[1].color)
  await page.evaluate(()=>{const a=(window as any).__neural,bonus=a.stateBonus;try{a.stateBonus=()=>0.3;a.refreshOptionOdds()}finally{a.stateBonus=bonus}})
  expect(await threats.locator('.ngodds').allTextContents()).toEqual(marks.map(m=>m.odds))
  await page.evaluate(()=>(window as any).__neural.refreshOptionOdds())
  await page.screenshot({path:'/tmp/submission-triangle-options.png'})
  const before=await page.evaluate(()=>{const a=(window as any).__neural;return [a.currentPos,a.playerRole,a.moveCount]})
  const threat=page.locator('[data-choice-group="opponent"] [data-opponent-threat]').filter({hasText:'Posture up'})
  await threat.scrollIntoViewIfNeeded();await threat.click()
  await expect(page.locator('[data-choice-preview]')).toContainText('Your opponent may attempt this')
  await expect(page.locator('[data-choice-go]')).toHaveCount(0)
  await page.keyboard.press('Enter')
  expect(await page.evaluate(()=>{const a=(window as any).__neural;return [a.currentPos,a.playerRole,a.moveCount]})).toEqual(before)
  await page.locator('[data-choice-close]').click()
  const kimura=own.locator('[data-tech="Kimura from Triangle Control"]')
  await kimura.scrollIntoViewIfNeeded();await kimura.click() // deterministic entry
  await j.advance(3000)
  await expect.poll(()=>page.evaluate(()=>(window as any).__neural.nodes[(window as any).__neural.currentPos].t)).toBe('Kimura from Triangle Control')
  await expect(own.locator('[data-choice-action="finish"]')).toHaveCount(1)
  await j.rig('resolve',[0]);await j.rig('outcome',[0])
  await own.locator('[data-choice-action="finish"]').click()
  await j.advance(8000)
  expect(await j.lastOutcome()).toBe('win')
  expect(errors).toEqual([])
})

test('@curated triangle defender sees escape actions and can preview the opponent finish without executing it',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  const j=journey(page)
  await j.boot('/Submissions/Triangle-Choke/from-Triangle-Control/Defender')
  await j.advance(4000)
  const own=page.locator('[data-choice-group="you"]')
  await expect(own).toContainText('Posture up')
  await expect(own).toContainText('Stack escape')
  await expect(own.locator('[data-choice-action="finish"]')).toHaveCount(0)
  await expect(page.locator('[data-choice-group="opponent"] [data-choice-action="finish"]')).toHaveCount(1)
  const finish=page.locator('[data-choice-group="opponent"] [data-choice-action="finish"]')
  await expect.poll(()=>page.locator('[data-legend-win]').getAttribute('data-win-chance'),{timeout:45_000}).toMatch(/%$/)
  const vs=await page.locator('[data-legend-win]').getAttribute('data-win-chance')
  await expect(finish.locator('[data-threat-win]')).toHaveText(vs!)
  await expect(finish.locator('[data-threat-win]')).toHaveAttribute('title',/You are defending this now/)
  await expect(finish.locator('.ngbotrow > div')).toHaveText('Odds')
  const finishOdds=await finish.locator('.ngodds').textContent()
  await page.evaluate(()=>(window as any).__neural.refreshEscapeOdds())
  await expect(finish.locator('.ngodds')).toHaveText(finishOdds!)
  // The hand sorted itself ONCE when its values arrived (owner, 2026-09-29), so an escape's key is
  // its CURRENT place in the tray, read off the tray.
  const key=String((await own.locator('.ngchoice-title').allTextContents()).findIndex(t=>t.trim()==='Posture up')+1)
  expect(key,'Posture up is in the tray').not.toBe('0')
  await page.keyboard.press(key)
  await expect(page.locator('[data-choice-preview]')).toContainText('Posture up')
  await expect(page.locator('[data-choice-go]')).toHaveText('Posture up')
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-choice-preview]')).not.toBeVisible()
  await j.rig('escape',[0])
  await page.keyboard.press(key);await page.locator('[data-choice-go]').click()
  await j.advance(4000)
  const landed=await page.evaluate(()=>{const a=(window as any).__neural;return {role:a.playerRole,position:a.nodes[a.currentPos].posId,history:a.rollLog.map((r:any)=>r.key)}})
  expect(landed.role).toBe('top')
  expect(landed.position).toBe('open-guard')
  expect(landed.history).toContain('Triangle Choke from Triangle Control|Defender')
  expect(errors).toEqual([])
})

// A late response must not put the player back into a submission they already left.
test('@curated a slow submission payload holds its choices and cannot overwrite a later landing',async({page})=>{
  const j=journey(page), pattern='**/submission-details/*.json'
  await j.boot('/Submissions/Triangle-Choke/from-Triangle-Control/Defender',{payloads:{[pattern]:{never:true}}})
  await j.advance(4000)
  await expect(page.getByRole('status').filter({hasText:'Loading submission choices'})).toBeVisible()
  await expect(page.locator('[data-choice-group]')).toHaveCount(0)
  await page.evaluate(()=>{const a=(window as any).__neural;const n=a.nodes.find((n:any)=>n.ty==='positions'&&n.posId==='mount'&&n.role==='top');a.rollFromPosition(n.idx,true,'top')})
  await j.advance(2000)
  await j.releasePayload(pattern)
  await expect(page.locator('[data-choice-group="you"]')).toBeVisible()
  await j.advance(2000)
  expect(await page.evaluate(()=>{const a=(window as any).__neural;return a.nodes[a.currentPos].posId})).toBe('mount')
})
