/**
 * /l/<code> — the share-link edge tier (Cloudflare Pages Function).
 *
 * THIS TIER IS OPTIONAL BY DESIGN. Everything a recipient actually does — the lit graph, the
 * named list, drilling the class — happens in the browser off the plain static shell, reached
 * by the `/l/* /l.html 200` rewrite in `_redirects`. If this file never builds, never deploys,
 * or throws, the feature still works and only the social preview degrades to generic text.
 * e2e/journeys/share-lists.spec.ts tests that rung explicitly, with no Function in the path.
 *
 * What this tier adds, and the only thing it adds: WhatsApp, Telegram, X and Slack fetch a
 * shared URL SERVER-SIDE and never run JavaScript. So "these are the techniques we learned in
 * today's class" can only reach the group-chat preview from the edge. Here we decode the code,
 * look the names up in the emitted ordinal manifest, and write them into og:title /
 * og:description.
 *
 * Two placement facts this file depends on (both verified in this repo, the hard way):
 *   · A `functions/` directory at the REPO ROOT *is* picked up by
 *     `wrangler pages deploy source/public` — proven live by functions/ping.js.
 *   · It must NOT live in `source/public/functions/`: Quartz's build rimrafs source/public,
 *     wrangler resolves `functions` from cwd, and Pages' uploader excludes a `functions`
 *     directory from the asset upload. Three silent deaths, no warning.
 *
 * Plain .js (like ping.js), not .ts: this repo has no @cloudflare/workers-types, and the pure
 * helpers are imported by `node --test` (tests/share_lists_store.test.mjs) from the SAME source
 * the browser bundle uses — one codec, one og-text implementation, no drift.
 */

import { ngListDecodeOrdinals } from "../../neural/src/lists-codec.src.js";
import {
  ngListParseSharePath,
  ngShareOgTitle,
  ngShareOgDescription,
} from "../../neural/src/lists.src.js";

const SHELL_PATH = "/l.html";
const MANIFEST_PATH = "/l-manifest.json";

// ── HEADERS: this Function is the ONLY header source for the URLs it answers ───────────────
// Cloudflare, verbatim: "Custom headers defined in the _headers file are not applied to
// responses generated by Pages Functions, even if the request URL matches a rule defined in
// _headers." (https://developers.cloudflare.com/pages/configuration/headers/)
//
// So `/l/<code>` has TWO header sources that never overlap: this file when the Function is
// deployed, `_headers` when it is not (the `/l/* -> /l.html 200` rewrite rung). There is no
// comma-join to worry about here — there is a WORSE failure available, which is the two
// disagreeing, so that a share link's TTL and security posture change the day the Function
// lands. Both constants below are kept BYTE-IDENTICAL to source/quartz/static/_headers and
// scripts/check_headers_cache.py fails the build if either drifts.
//
// Same tier as content HTML deliberately: a short browser max-age so a deploy propagates, and
// SWR so the edge answers instantly and revalidates behind the request. (The earlier
// `s-maxage=86400` here was the drift: it pinned the edge for a day on the Function rung only.)
const SHARE_CACHE_CONTROL = "public, max-age=300, stale-while-revalidate=3600";

// The `/*` block of _headers, re-applied by hand because Pages will not apply it for us.
const SHARE_STATIC_HEADERS = {
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "SAMEORIGIN",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "geolocation=(), microphone=(), camera=(), interest-cohort=()",
  "Strict-Transport-Security": "max-age=63072000; includeSubDomains; preload",
  "Content-Security-Policy-Report-Only": "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; img-src 'self' data: https: blob:; font-src 'self' data: https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://*.posthog.com https://*.i.posthog.com https://www.clarity.ms; connect-src 'self' https://*.supabase.co https://*.posthog.com https://*.i.posthog.com https://www.clarity.ms; worker-src 'self' blob:; manifest-src 'self'; frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com",
};

/** Rewrite the marked <meta> tags. `data-share-og="<field>"` is written by
 *  scripts/build_share_shell.mjs — that attribute IS the contract between the two files. */
class OgMeta {
  constructor(values) {
    this.values = values;
  }
  element(el) {
    const field = el.getAttribute("data-share-og");
    const value = field ? this.values[field] : null;
    // setAttribute escapes on its own — the helpers deliberately return plain, unescaped text
    if (value) el.setAttribute("content", value);
  }
}

/** The document title. Selected by its MARKER (`title[data-share-title]`, written by
 *  scripts/build_share_shell.mjs), never by bare `title`: HTMLRewriter matches by element name,
 *  and this shell holds a second one — `<title>Search</title>` inside the search button's inline
 *  SVG. A bare `title` selector rewrote that too, replacing the accessible name of a control with
 *  the shared class's technique list. Same contract shape as `meta[data-share-og]`. */
class TitleText {
  constructor(title) {
    this.title = title;
  }
  element(el) {
    el.setInnerContent(this.title);
  }
}

/** A marker so a human (and the e2e suite) can tell an edge-rendered response from the plain
 *  shell at a glance: `document.documentElement.dataset.shareOg`. */
class HtmlMarker {
  element(el) {
    el.setAttribute("data-share-og", "1");
  }
}

export async function onRequest(context) {
  const { request, env } = context;
  const url = new URL(request.url);

  // The shell is the one source of truth for the page. Fetch it by its own path so this never
  // depends on how the rewrite is configured.
  let shell;
  try {
    shell = await env.ASSETS.fetch(new URL(SHELL_PATH, url));
  } catch (e) {
    shell = null;
  }
  if (!shell || !shell.ok) {
    // No shell in this deployment: hand the request back to the static layer rather than
    // inventing a page. Worst case the visitor gets the 404, which is honest.
    return env.ASSETS.fetch(request);
  }

  const code = ngListParseSharePath(url.pathname + url.search);
  const decoded = code ? ngListDecodeOrdinals(code) : { ok: false };
  if (!decoded.ok) return withHeaders(shell, code ? "invalid" : "none");

  // ordinal -> technique name (emitted by scripts/build_share_shell.mjs). Optional: without it
  // the preview stays generic, which is exactly the no-Function behaviour.
  let names = null;
  try {
    const res = await env.ASSETS.fetch(new URL(MANIFEST_PATH, url));
    if (res && res.ok) {
      const json = await res.json();
      names = json && json.names ? json.names : null;
    }
  } catch (e) {
    names = null;
  }
  if (!names) return withHeaders(shell, "no-manifest");

  const resolved = [];
  for (const o of decoded.ordinals) {
    const name = names[String(o)];
    if (typeof name === "string" && name) resolved.push(name);
  }
  if (!resolved.length) return withHeaders(shell, "unresolved");

  const values = {
    title: ngShareOgTitle(resolved, decoded.ordinals.length),
    description: ngShareOgDescription(resolved, decoded.ordinals.length),
    url: url.origin + "/l/" + code,
  };
  const out = new HTMLRewriter()
    .on("html", new HtmlMarker())
    .on("title[data-share-title]", new TitleText(values.title))
    .on("meta[data-share-og]", new OgMeta(values))
    .transform(shell);
  return withHeaders(out, "ok", resolved.length);
}

function withHeaders(res, state, count) {
  const headers = new Headers(res.headers);
  // ENTITY HEADERS DESCRIBE A BODY, and the body we return is not always the body we were
  // handed: on the `ok` path it has been through HTMLRewriter, so it is a different length
  // with a different hash. Copying the asset's Content-Length ships a wrong length (a
  // truncated or hung response, depending on the client) and copying its ETag/Last-Modified
  // makes two DIFFERENT documents — the plain shell and the og-rendered one — claim the same
  // cache validator, so a conditional request can be answered with the wrong one. Drop them
  // and let the runtime compute what it needs.
  headers.delete("content-length");
  headers.delete("etag");
  headers.delete("last-modified");
  headers.delete("content-encoding"); // ASSETS.fetch hands us a decoded body
  headers.set("content-type", "text/html; charset=utf-8");
  headers.set("cache-control", SHARE_CACHE_CONTROL);
  // _headers cannot reach a Function response (see the note beside the constants) — so every
  // header the rest of the site gets from `/*` has to be set right here.
  for (const [k, v] of Object.entries(SHARE_STATIC_HEADERS)) headers.set(k, v);
  // Belt AND braces with the shell's <meta name="robots">: a share URL is never content.
  headers.set("x-robots-tag", "noindex, nofollow");
  headers.set("x-share-og", count ? state + ":" + count : state);
  return new Response(res.body, { status: 200, headers: headers });
}
