import matter from "gray-matter"
import remarkFrontmatter from "remark-frontmatter"
import { QuartzTransformerPlugin } from "../types"
import yaml from "js-yaml"
import { slugTag } from "../../util/path"
import { QuartzPluginData } from "../vfile"
import { i18n } from "../../i18n"

export interface Options {
  delimiters: string | [string, string]
  // TOML frontmatter support was REMOVED (v1.192.5), and with it the `toml` package, which
  // carried two high-severity advisories: GHSA-v5mp-jgw5-2x6j (prototype pollution) and
  // GHSA-82x6-q7mm-w9cf (uncontrolled recursion). Evidence it was unreachable: 0 of 4,600
  // content/*.md open with `+++`, every one of them is GENERATED by
  // scripts/regenerate_md_from_json.py through templates/*.jinja2, which emit YAML only, and
  // Plugin.FrontMatter() is constructed with no options (quartz.config.ts) so this defaulted
  // to "yaml" anyway. THIS IS A CAPABILITY REMOVAL, not a no-op: a `+++` block authored after
  // this point is no longer recognised as frontmatter at all — it renders as body text, with
  // no error. Re-adding it means reinstating the dependency, not just the delimiter.
  // RECOMPUTE the reachability claim:
  //   grep -rlFx '+++' content --include='*.md' | wc -l          -> 0 (of 4,600)
  //   grep -rn -- '+++' templates/ scripts/regenerate_md_from_json.py  -> no match
  language: "yaml"
}

const defaultOptions: Options = {
  delimiters: "---",
  language: "yaml",
}

function coalesceAliases(data: { [key: string]: any }, aliases: string[]) {
  for (const alias of aliases) {
    if (data[alias] !== undefined && data[alias] !== null) return data[alias]
  }
}

function coerceToArray(input: string | string[]): string[] | undefined {
  if (input === undefined || input === null) return undefined

  // coerce to array
  if (!Array.isArray(input)) {
    input = input
      .toString()
      .split(",")
      .map((tag: string) => tag.trim())
  }

  // remove all non-strings
  return input
    .filter((tag: unknown) => typeof tag === "string" || typeof tag === "number")
    .map((tag: string | number) => tag.toString())
}

export const FrontMatter: QuartzTransformerPlugin<Partial<Options>> = (userOpts) => {
  const opts = { ...defaultOptions, ...userOpts }
  return {
    name: "FrontMatter",
    markdownPlugins({ cfg }) {
      return [
        [remarkFrontmatter, ["yaml"]],
        () => {
          return (_, file) => {
            const { data } = matter(Buffer.from(file.value), {
              ...opts,
              engines: {
                yaml: (s) => yaml.load(s, { schema: yaml.JSON_SCHEMA }) as object,
              },
            })

            if (data.title != null && data.title.toString() !== "") {
              data.title = data.title.toString()
            } else {
              data.title = file.stem ?? i18n(cfg.configuration.locale).propertyDefaults.title
            }

            const tags = coerceToArray(coalesceAliases(data, ["tags", "tag"]))
            if (tags) data.tags = [...new Set(tags.map((tag: string) => slugTag(tag)))]

            const aliases = coerceToArray(coalesceAliases(data, ["aliases", "alias"]))
            if (aliases) data.aliases = aliases
            const cssclasses = coerceToArray(coalesceAliases(data, ["cssclasses", "cssclass"]))
            if (cssclasses) data.cssclasses = cssclasses

            // fill in frontmatter
            file.data.frontmatter = data as QuartzPluginData["frontmatter"]
          }
        },
      ]
    },
  }
}

declare module "vfile" {
  interface DataMap {
    frontmatter: { [key: string]: unknown } & {
      title: string
    } & Partial<{
        tags: string[]
        aliases: string[]
        description: string
        publish: boolean
        draft: boolean
        lang: string
        enableToc: string
        cssclasses: string[]
        // Opt a route out of search indexing (Head.tsx emits <meta name="robots">). For pages
        // that must stay REACHABLE — internal links point at them — but carry no indexable
        // content of their own. See content/Game Over.md.
        noindex: boolean
      }>
  }
}
