#!/usr/bin/env python3
"""
THE CATEGORY INDEX PAGES MATCH THEIR GENERATOR — a parity gate (v1.215.7).

`content/<Category>.md` (Positions, Transitions, Submissions, Systems, Principles, Learning) are
GENERATED by scripts/regenerate_category_hub_pages.py from every leaf JSON in that category, and —
like every generated .md here — they carry no do-not-edit banner (CLAUDE.md §1). Regeneration is
keyed on the file that was EDITED, so editing a leaf leaves its index page stale, and a stale page
looks exactly like a fresh one (CLAUDE.md §6.6).

That is what happened: v1.191.0 (95291a1c3, 2026-09-20) rewrote all 62 Principles descriptions and
regenerated the leaves but not the index, which kept listing the old promotional blurbs for 11 days;
v1.205.0 then spliced only Microing's hunks of a full regeneration into it, holding the other 62 at
their stale text. Nothing failed, because nothing compared the page with its generator.

This renders every category index page IN MEMORY with the generator's own code (nothing is written)
and compares it, byte for byte, with the committed file — exactly what `npm run regenerate:hubs`
would write. It fails on any difference, naming the page and its first differing line, and it
fails when it checked nothing (no categories, a category with no leaves, a missing page): a gate
that looked at zero pages must never read like a clean pass. One positive line either way.

Stdlib only (plus the generator and scripts/_slug.py), so it runs in ci-validate.yml, which
installs no numpy. ~0.5 s.

    python3 scripts/check_category_hubs.py                 # the gate
    python3 scripts/check_category_hubs.py --content-dir X # negative controls (tests/)

Fix a red: `npm run regenerate:hubs`, commit the regenerated page. Never hand-edit it, and never
commit part of a regeneration.
"""
import argparse
import collections
import contextlib
import io
import os
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS))
import regenerate_category_hub_pages as hubs  # noqa: E402


def check(content_dir: Path) -> tuple:
    """Return (problems, checked, in_sync, lines) for every category the generator knows."""
    problems, lines = [], []
    checked = in_sync = 0
    gen = hubs.CategoryHubPageGenerator(source_dir=str(content_dir))
    if not gen.categories:
        return ["the generator knows no categories"], 0, 0, lines
    for cat in gen.categories:
        with contextlib.redirect_stdout(io.StringIO()):  # the generator narrates; we report
            items = gen.scan_directory(cat)
            page = gen.generate_hub_page(cat, items) if items else None
        if not items:
            problems.append(f"{cat}: the generator found NO leaves under {content_dir / cat} — nothing to compare")
            continue
        committed_path = content_dir / f"{cat}.md"
        if not committed_path.exists():
            problems.append(f"{cat}: {committed_path} is missing — the index page was never generated")
            continue
        # newline="" so the comparison sees the committed bytes, not a translated view of them
        with open(committed_path, encoding="utf-8", newline="") as f:  # Path.read_text(newline=) is 3.13+
            committed = f.read()
        checked += 1
        if committed == page:
            in_sync += 1
            lines.append(f"  {cat}: {len(items)} items, in sync")
            continue
        # LINEAR summary on purpose: a stale Transitions page is ~6,000 lines, and difflib's
        # matcher is quadratic there. The gate's verdict is the byte comparison above; this only
        # names the first differing line and counts the lines on each side that the other lacks.
        old, new = committed.splitlines(), page.splitlines()
        i = next((k for k, (x, y) in enumerate(zip(old, new)) if x != y), min(len(old), len(new)))
        ln, was, now = i + 1, old[i] if i < len(old) else "", new[i] if i < len(new) else ""
        co, cn = collections.Counter(old), collections.Counter(new)
        removed, added = sum((co - cn).values()), sum((cn - co).values())
        problems.append(
            f"{cat}: STALE — {committed_path} differs from its generator "
            f"({removed} line(s) committed, {added} regenerated; {len(items)} items). "
            f"First difference at line {ln}:\n      committed: {was[:160]}\n      generator: {now[:160]}"
        )
        lines.append(f"  {cat}: {len(items)} items, STALE")
    if gen.files_needing_json_fix:
        problems.append(f"{len(gen.files_needing_json_fix)} leaf JSON file(s) failed to parse: "
                        + ", ".join(str(p) for p in gen.files_needing_json_fix[:5]))
    return problems, checked, in_sync, lines


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--content-dir", default="content")
    args = ap.parse_args()
    # RENDER EXACTLY AS `npm run regenerate:hubs` DOES: from the repo root, with the RELATIVE
    # "content". The generator builds every wikilink from the path it was given, so an absolute
    # source dir writes `[[/home/…/content/Positions/…]]` into all six pages — each one would "drift"
    # (measured while writing this gate).
    os.chdir(SCRIPTS.parent)
    problems, checked, in_sync, lines = check(Path(args.content_dir))
    if checked == 0 and not problems:
        problems.append("checked ZERO index pages — a gate that looked at nothing is not a pass")
    print(f"[category-hubs] {checked} index page(s) checked, {in_sync} in sync")
    for line in lines:
        print(line)
    if problems:
        print(f"[category-hubs] FAIL — {len(problems)} problem(s):")
        for p in problems:
            print(f"  - {p}")
        print("  Fix: `npm run regenerate:hubs` and commit the regenerated page(s). Never hand-edit a "
              "generated .md, and never commit part of a regeneration (CLAUDE.md §1).")
        return 1
    print("[category-hubs] OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
