#!/usr/bin/env python3
"""check_headers_cache.py — prove the _headers cache tiers stay DISJOINT.

Why this exists (v1.77.0): Cloudflare's `_headers` contract is
    "An incoming request which matches multiple rules' URL patterns will inherit
     all rules' headers"
and
    "If a header is applied twice in the _headers file, the values are joined with
     a comma separator."

So two matching `Cache-Control` rules produce
    Cache-Control: public, max-age=300, ..., public, max-age=14400, ...
and the FIRST max-age wins. A single careless `/*` Cache-Control rule would
therefore cap the 38MB Neural data layer at the HTML TTL — with no error, no
warning, and no local symptom. Only the field metrics would move the wrong way,
weeks later.

This gate fails the build instead. It asserts:
  1. every probe path matches AT MOST ONE Cache-Control rule;
  2. `/*` never carries Cache-Control;
  3. no rule pattern is defined twice;
  4. Cloudflare's limits hold (<=100 rule blocks, <=2000 chars/line);
  5. `immutable` is absent — every asset here changes under a fixed URL on deploy,
     so immutable would pin stale bundles in browsers for the whole max-age.

SECOND CLASS, added v1.81.2 — A PATH SERVED FROM TWO PLACES. `_headers` is NOT the
only thing that can set Cache-Control. Cloudflare's documented rule is:

    "Custom headers defined in the _headers file are not applied to responses
     generated by Pages Functions, even if the request URL matches a rule defined
     in _headers."
    https://developers.cloudflare.com/pages/configuration/headers/

So a path covered by BOTH a Pages Function and a `_headers` rule has TWO
independent header sources and which one answers depends on whether the Function
is deployed at all. `/l/*` is exactly that path: the Function adds the social
preview, and the `/l/* -> /l.html 200` rewrite serves the same URL when the
Function is absent (which is a supported, tested rung). If the two disagree, the
share link's TTL silently changes the day the Function lands — invisible locally,
invisible in review. So this gate also asserts, for every Pages Function route:
  6. the Function's Cache-Control is BYTE-IDENTICAL to the `_headers` rule for the
     same path (one tier, two emitters, no drift);
  7. a Function that TRANSFORMS the body deletes Content-Length and ETag before
     re-using the upstream asset's headers (a copied Content-Length is a wrong
     length and a copied ETag makes two different bodies share a cache key);
  8. the Function re-applies the site-wide `/*` security headers verbatim, since
     `_headers` will not do it for a Function response. Missing keys and drifted
     VALUES are hard errors (text can answer "are these two strings equal?").
     Whether the declared object is actually WRITTEN into the response is only a
     WARNING: that question needs a JS semantics, not a regex, and this script runs
     inside `npm run build` — a false positive there would take the build down for a
     Function that was correct all along.

Checks the CANONICAL source (source/quartz/static/_headers) and, when present, the
emitted deploy-root copy (source/public/_headers) that regenerate_headers.py writes.

Usage:  python3 scripts/check_headers_cache.py
Exit:   0 = disjoint, 1 = a rule overlap or limit breach ships otherwise.
"""

from __future__ import annotations

import fnmatch
import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CANONICAL = PROJECT_ROOT / "source" / "quartz" / "static" / "_headers"
EMITTED = PROJECT_ROOT / "source" / "public" / "_headers"
FUNCTIONS = PROJECT_ROOT / "functions"

CF_MAX_RULES = 100
CF_MAX_LINE = 2000

# Representative request paths: one per tier plus the deliberately-uncached ones.
PROBE_PATHS = (
    "/",
    "/Positions",
    "/Positions/Mount/Top",
    "/Transitions",
    "/Transitions/Armbar-from-Mount",
    "/Submissions/Rear-Naked-Choke",
    "/Principles/Frames",
    "/Systems/Leg-Lock-System",
    "/Learning/Fundamentals",
    "/tags/guard",
    "/Game-Over",
    "/Tree",
    "/l/AQID",
    "/l.html",
    "/l-manifest.json",
    "/terms",
    "/privacy",
    "/index.css",
    "/prescript.js",
    "/postscript.js",
    "/static/og-image.png",
    "/static/neural/app/neural.js",
    "/static/neural/graph-data.json",
    "/static/neural/flashcards/_index.json",
    "/static/neural/flashcards/mount__top.json",
    "/sitemap.xml",
    "/index.xml",
    "/llms.txt",
    "/404.html",
    "/dev/screens/",
)


def parse(path: Path) -> list[tuple[str, list[str]]]:
    """[(url_pattern, [header lines])] in file order."""
    blocks: list[tuple[str, list[str]]] = []
    for raw in path.read_text().splitlines():
        if raw.strip().startswith("#") or not raw.strip():
            continue
        if raw.startswith("/"):
            blocks.append((raw.strip(), []))
        elif blocks:
            blocks[-1][1].append(raw.strip())
    return blocks


def matches(pattern: str, url: str) -> bool:
    return fnmatch.fnmatchcase(url, pattern) if "*" in pattern else pattern == url


def check(path: Path) -> list[str]:
    errors: list[str] = []
    blocks = parse(path)
    label = path.relative_to(PROJECT_ROOT)

    if len(blocks) > CF_MAX_RULES:
        errors.append(f"{label}: {len(blocks)} rule blocks exceeds Cloudflare's {CF_MAX_RULES}")

    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        if len(raw) > CF_MAX_LINE:
            errors.append(f"{label}:{lineno}: line is {len(raw)} chars (Cloudflare cap {CF_MAX_LINE})")

    patterns = [p for p, _ in blocks]
    for dupe in sorted({p for p in patterns if patterns.count(p) > 1}):
        errors.append(f"{label}: pattern {dupe!r} defined more than once — headers would comma-join")

    cache_rules = [
        (p, h) for p, headers in blocks for h in headers if h.lower().startswith("cache-control:")
    ]

    for pattern, header in cache_rules:
        if pattern == "/*":
            errors.append(
                f"{label}: /* carries Cache-Control ({header!r}) — it matches EVERY path, so its "
                f"max-age would comma-join ahead of every specific tier and win. Move it to "
                f"disjoint prefixes."
            )
        if "immutable" in header.lower():
            errors.append(
                f"{label}: {pattern} sets `immutable` — these URLs are not content-hashed and "
                f"change on every deploy, so browsers would pin a stale bundle for the full max-age."
            )

    for url in PROBE_PATHS:
        hits = [p for p, _ in cache_rules if matches(p, url)]
        if len(hits) > 1:
            errors.append(
                f"{label}: {url} matches {len(hits)} Cache-Control rules {hits} — Cloudflare joins "
                f"them with a comma and the first max-age wins. Make them disjoint."
            )
    return errors


# ── Pages Functions: the SECOND header source for the paths they own ──────────────────


def function_route(path: Path) -> str:
    """functions/l/[[path]].js -> "/l/*"   ·   functions/ping.js -> "/ping".

    Cloudflare Pages routing: a file's path IS its route; `[[name]]` is a catch-all and
    `[name]` is a single segment.
    """
    rel = path.relative_to(FUNCTIONS).with_suffix("")
    parts = []
    for seg in rel.parts:
        if seg.startswith("[[") and seg.endswith("]]"):
            parts.append("*")
        elif seg.startswith("[") and seg.endswith("]"):
            parts.append("*")
        else:
            parts.append(seg)
    if parts and parts[-1] == "index":
        parts.pop()
    return "/" + "/".join(parts)


def probe_for(route: str) -> str:
    """A concrete request path that hits this route (so it can be matched against rules)."""
    return route.replace("/*", "/AQID") if route.endswith("/*") else route


def js_object(src: str, name: str) -> dict[str, str] | None:
    """Parse `const NAME = { "a": "b", … };` — the Function's declared header block."""
    m = re.search(r"const\s+" + re.escape(name) + r"\s*=\s*\{(.*?)\n\};", src, re.S)
    if not m:
        return None
    body = re.sub(r",(\s*)$", r"\1", m.group(1).strip())
    try:
        return json.loads("{" + body + "}")
    except json.JSONDecodeError:
        return None


def check_functions(headers_path: Path, warnings: list[str] | None = None) -> list[str]:
    """Hard errors are returned; advisory findings are appended to `warnings` (see 8a)."""
    errors: list[str] = []
    if warnings is None:
        warnings = []
    if not FUNCTIONS.is_dir():
        return errors
    blocks = parse(headers_path)
    label = headers_path.relative_to(PROJECT_ROOT)
    star = {}
    for pattern, hs in blocks:
        if pattern != "/*":
            continue
        for h in hs:
            k, _, v = h.partition(":")
            star[k.strip().lower()] = (k.strip(), v.strip())

    for fn in sorted(FUNCTIONS.rglob("*.js")):
        src = fn.read_text()
        if "onRequest" not in src:
            continue
        route = function_route(fn)
        probe = probe_for(route)
        fnlabel = fn.relative_to(PROJECT_ROOT)

        # (6) Cache-Control: one tier, two emitters, byte-identical.
        set_values = [
            v
            for k, v in re.findall(r'headers\.set\(\s*"([^"]+)"\s*,\s*"([^"]*)"\s*\)', src)
            if k.lower() == "cache-control"
        ]
        set_values += [
            m
            for m in re.findall(
                r'headers\.set\(\s*"[Cc]ache-[Cc]ontrol"\s*,\s*([A-Z_][A-Z0-9_]*)\s*\)', src
            )
        ]
        named = {
            n: v
            for n, v in re.findall(r'const\s+([A-Z_][A-Z0-9_]*)\s*=\s*"([^"]*)"\s*;', src)
        }
        resolved = [named.get(v, v) for v in set_values]
        rules = [
            h.partition(":")[2].strip()
            for p, hs in blocks
            for h in hs
            if h.lower().startswith("cache-control:") and matches(p, probe)
        ]
        # (6a) OMISSION, not just drift. The loop below compares the values a Function DOES set;
        # if a Function stops setting Cache-Control at all, `resolved` is empty and the loop body
        # never runs — so deleting the line was invisible while changing it was caught. That is
        # backwards: `_headers` does not apply to a Function response, so an omitted Cache-Control
        # means this path silently loses its whole tier the day the Function deploys, which is the
        # exact hazard this gate exists for. A path with a tier in `_headers` must have one here.
        if rules and not resolved:
            errors.append(
                f"{fnlabel}: sets NO Cache-Control for {route}, but {label} gives {probe} "
                f"{rules[0]!r}. `_headers` does not apply to Function responses, so this path "
                f"would ship with whatever the CDN defaults to the moment the Function deploys. "
                f"Set it here too, byte-identical."
            )
        for value in resolved:
            if not rules:
                errors.append(
                    f"{fnlabel}: sets Cache-Control {value!r} for {route}, but {label} has no "
                    f"Cache-Control rule matching {probe} — the no-Function rung (the "
                    f"`/l/* -> /l.html 200` rewrite) would ship uncached."
                )
            elif value not in rules:
                errors.append(
                    f"{fnlabel}: sets Cache-Control {value!r} while {label} says {rules[0]!r} for "
                    f"{probe}. _headers does NOT apply to Function responses, so this path's TTL "
                    f"silently changes depending on whether the Function is deployed. Make them "
                    f"byte-identical."
                )

        # (7) a transformed body must not inherit the asset's entity headers.
        # last-modified is a VALIDATOR exactly like etag (a conditional request can be answered
        # from it), and content-encoding describes bytes that ASSETS.fetch already decoded — a
        # surviving `gzip` makes the browser fail to decode the page at all.
        if "HTMLRewriter" in src:
            for entity in ("content-length", "etag", "last-modified", "content-encoding"):
                if not re.search(r'headers\.delete\(\s*"' + entity + r'"\s*\)', src, re.I):
                    errors.append(
                        f"{fnlabel}: transforms the body with HTMLRewriter but never "
                        f'headers.delete("{entity}") — the upstream asset\'s {entity} describes a '
                        f"DIFFERENT body than the one being returned."
                    )

        # (8) the site-wide security headers, re-applied by hand (see the module docstring).
        # Scoped to Functions that return a DOCUMENT: X-Frame-Options, CSP and friends protect
        # HTML. A JSON endpoint (functions/ping.js) is not a framing or script-injection target.
        if "text/html" not in src:
            continue
        declared = js_object(src, "SHARE_STATIC_HEADERS")
        if star and declared is None:
            errors.append(
                f"{fnlabel}: no SHARE_STATIC_HEADERS block. `_headers` /* does not apply to a "
                f"Function response, so this route would ship with none of the {len(star)} "
                f"site-wide security headers."
            )
        elif star and declared is not None:
            # (8a) DECLARED IS NOT APPLIED — A WARNING, DELIBERATELY, NOT A GATE.
            # A correct SHARE_STATIC_HEADERS object that nothing writes into the response passes
            # every value comparison below while shipping none of the headers, so it is worth
            # saying something about. But "is it applied?" cannot be answered by reading text: the
            # first version of this check required a literal `headers.set(` within 240 characters
            # of a use, which is satisfied by luck and broken by any legitimate refactor — a helper
            # in another module, a `new Headers({...SHARE_STATIC_HEADERS})`, an `Object.entries`
            # loop, or simply more than 240 characters of code. And this script runs INSIDE
            # `npm run build`, so a false positive there does not flag a header: it takes the whole
            # build down for a Function that was right all along. A gate with false positives on
            # the build path is worse than no gate, so this reports and the build continues; the
            # DRIFT and OMISSION checks around it stay hard errors because they compare values,
            # which text can actually answer.
            uses = [
                m.start()
                for m in re.finditer(r"\bSHARE_STATIC_HEADERS\b", src)
                if not re.search(r"const\s+$", src[max(0, m.start() - 12) : m.start()])
            ]
            applied = re.compile(
                r"headers\.set\(|new\s+Headers\s*\(|Object\.(entries|keys|assign)\s*\(|"
                r"\.\.\.SHARE_STATIC_HEADERS|for\s*\(|\.forEach\s*\(|withHeaders\s*\("
            )
            if not uses:
                warnings.append(
                    f"{fnlabel}: SHARE_STATIC_HEADERS is declared and never referenced again — "
                    f"nothing can be writing it into the response."
                )
            elif not any(applied.search(src[max(0, u - 120) : u + 400]) for u in uses):
                warnings.append(
                    f"{fnlabel}: could not see SHARE_STATIC_HEADERS being written into a response "
                    f"near any of its {len(uses)} use(s). If it IS applied (a helper, a spread, a "
                    f"loop), ignore this line — it is a text search, not a proof."
                )
            lower = {k.lower(): v for k, v in declared.items()}
            for key, (orig, value) in star.items():
                if key not in lower:
                    errors.append(
                        f"{fnlabel}: SHARE_STATIC_HEADERS is missing {orig!r}, which {label} "
                        f"applies to every other response."
                    )
                elif lower[key] != value:
                    errors.append(
                        f"{fnlabel}: SHARE_STATIC_HEADERS[{orig!r}] has drifted from {label} "
                        f"(function: {lower[key]!r} · _headers: {value!r})."
                    )
    return errors


def main() -> None:
    targets = [p for p in (CANONICAL, EMITTED) if p.exists()]
    if not targets:
        print(f"[check_headers_cache] ERROR: no _headers found at {CANONICAL}", file=sys.stderr)
        sys.exit(1)

    errors: list[str] = []
    warnings: list[str] = []
    for target in targets:
        errors.extend(check(target))
        # …and the Function checks against EVERY _headers we have, not just the canonical one.
        # Cloudflare reads the EMITTED source/public/_headers; the canonical
        # source/quartz/static/_headers is only its input. regenerate_headers.py sits between
        # them and can add, drop or reorder rules, so a Function/`_headers` disagreement can
        # exist in the file that actually ships while the canonical pair agrees perfectly.
        errors.extend(check_functions(target, warnings))

    # the Function checks now run once per _headers file, and findings that name no file (the
    # Function-internal ones) come out identical twice — report each distinct finding once
    errors = list(dict.fromkeys(errors))
    warnings = list(dict.fromkeys(warnings))
    for warn in warnings:
        print(f"[check_headers_cache] WARNING: {warn}", file=sys.stderr)

    if errors:
        print("[check_headers_cache] FAIL", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        sys.exit(1)

    tiers = {}
    for pattern, header in (
        (p, h) for p, hs in parse(targets[0]) for h in hs if h.lower().startswith("cache-control:")
    ):
        age = header.split("max-age=")[1].split(",")[0] if "max-age=" in header else "?"
        tiers.setdefault(age, []).append(pattern)
    summary = " · ".join(f"max-age={age}: {len(pats)} rule(s)" for age, pats in sorted(tiers.items(), key=lambda kv: int(kv[0])))
    print(f"[check_headers_cache] OK — {len(targets)} file(s) checked, tiers disjoint. {summary}")


if __name__ == "__main__":
    main()
