#!/usr/bin/env python3
"""regenerate_llms_txt.py — emit source/public/llms.txt for LLM crawlers.

The /llms.txt convention (https://llmstxt.org) gives AI answer engines a curated,
machine-readable index of the site: a title, a one-paragraph description, and
sectioned links to the important pages. We list the category hubs plus the full
Positions / Principles / Systems / Learning sets (small, high-value), and link the
hub only for the large Transitions / Submissions sets.

Mirrors regenerate_redirects.py (walks content/, writes to source/public/). Runs
after `npm run build` via the `postbuild` hook.
"""

from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = PROJECT_ROOT / "content"
PUBLIC_DIR = PROJECT_ROOT / "source" / "public"
OUTPUT = PUBLIC_DIR / "llms.txt"
BASE_URL = "https://bjjgraph.org"

# Category hubs (generated by regenerate_category_hub_pages.py).
HUBS = [
    ("Positions", "all BJJ positions (board states)"),
    ("Transitions", "techniques that move between positions"),
    ("Submissions", "finishing techniques"),
    ("Principles", "cross-position concepts and decision frameworks"),
    ("Systems", "expert game plans and methodologies"),
    ("Learning", "strategy, training, and competition articles"),
]
# Enumerated in full (small, high-value). Large sets (Transitions/Submissions) are
# linked at the hub only to keep the index curated rather than exhaustive.
LISTED = ("Positions", "Principles", "Systems", "Learning")
LINKED_ONLY = ("Transitions", "Submissions")


def canonical_url(json_file: Path) -> str:
    """Canonical site URL for a content JSON file (case-preserved, spaces→hyphens)."""
    rel = json_file.relative_to(CONTENT_DIR).with_suffix("")
    return BASE_URL + "/" + "/".join(p.replace(" ", "-") for p in str(rel).split("/"))


def load_entries(category: str) -> list[tuple[str, str, str]]:
    """(name, url, description) for every content JSON in a category, sorted by name."""
    cat_dir = CONTENT_DIR / category
    entries: list[tuple[str, str, str]] = []
    if not cat_dir.exists():
        return entries
    for json_file in sorted(cat_dir.rglob("*.json")):
        if "TEMPLATE" in json_file.name:
            continue
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue
        if not isinstance(data, dict):
            continue
        name = (data.get("name") or json_file.stem).strip()
        desc = " ".join((data.get("summary") or data.get("description") or "").split())
        entries.append((name, canonical_url(json_file), desc))
    entries.sort(key=lambda e: e[0].lower())
    return entries


def count_files(category: str) -> int:
    cat_dir = CONTENT_DIR / category
    if not cat_dir.exists():
        return 0
    return sum(1 for f in cat_dir.rglob("*.json") if "TEMPLATE" not in f.name)


def main() -> None:
    counts = {cat: count_files(cat) for cat, _ in HUBS}

    lines: list[str] = []
    lines.append("# BJJ Graph")
    lines.append("")
    lines.append(
        "> Interactive Brazilian Jiu-Jitsu knowledge graph and state machine: "
        f"{counts['Positions']} positions, {counts['Transitions']} transitions, "
        f"{counts['Submissions']} submissions, {counts['Principles']} principles, and "
        f"{counts['Systems']} systems, modeled as a probabilistic "
        "Position → Transition → Position graph. Each page covers a technique or position "
        "with success rates, decision frameworks, and spaced-repetition flashcards."
    )
    lines.append("")

    lines.append("## Core")
    lines.append("")
    for cat, note in HUBS:
        lines.append(f"- [{cat}]({BASE_URL}/{cat}): {note}")
    lines.append("")

    for category in LISTED:
        entries = load_entries(category)
        if not entries:
            continue
        lines.append(f"## {category}")
        lines.append("")
        for name, url, desc in entries:
            lines.append(f"- [{name}]({url}){': ' + desc if desc else ''}")
        lines.append("")

    for category in LINKED_ONLY:
        lines.append(f"## {category}")
        lines.append("")
        lines.append(
            f"- [All {category.lower()}]({BASE_URL}/{category}): "
            f"{counts[category]} pages — browse the hub."
        )
        lines.append("")

    PUBLIC_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    total_listed = sum(len(load_entries(c)) for c in LISTED)
    print(f"[regenerate_llms_txt] Wrote {OUTPUT} ({total_listed} listed pages + hubs)")


if __name__ == "__main__":
    main()
