#!/usr/bin/env python3
"""regenerate_llms_txt.py — emit source/public/llms.txt for LLM crawlers.

The /llms.txt convention (https://llmstxt.org) gives AI answer engines a curated,
machine-readable index of the site: a title, a one-paragraph description, and
sectioned links to the important pages. We list the category hubs plus the full
Positions / Principles / Systems / Learning sets (small, high-value), and link the
hub only for the large Transitions / Submissions sets.

Mirrors regenerate_redirects.py (walks content/, writes to source/public/). Runs
inside local and deployment builds, after Quartz.
"""

from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = PROJECT_ROOT / "content"
PUBLIC_DIR = PROJECT_ROOT / "source" / "public"
OUTPUT = PUBLIC_DIR / "llms.txt"
BASE_URL = "https://bjjgraph.org"

# Category hubs (generated by regenerate_category_hub_pages.py).
HUBS = [
    ("Positions", "position guides, including top and bottom perspectives"),
    ("Transitions", "techniques that move between positions"),
    ("Submissions", "finishing techniques"),
    ("Principles", "cross-position concepts and decision frameworks"),
    ("Systems", "expert game plans and methodologies"),
    ("Learning", "strategy, training, and competition articles"),
]
# Enumerated in full (small, high-value). Large sets (Transitions/Submissions) are
# linked at the hub only to keep the index curated rather than exhaustive.
LISTED = ("Positions", "Principles", "Systems", "Learning")
LINKED_ONLY = ("Transitions", "Submissions")


def canonical_url(json_file: Path) -> str:
    """Canonical site URL for a content JSON file (case-preserved, spaces→hyphens)."""
    rel = json_file.relative_to(CONTENT_DIR).with_suffix("")
    return BASE_URL + "/" + "/".join(p.replace(" ", "-") for p in str(rel).split("/"))


def load_entries(category: str) -> list[tuple[str, str, str]]:
    """(name, url, description) for every content JSON in a category, sorted by name."""
    cat_dir = CONTENT_DIR / category
    entries: list[tuple[str, str, str]] = []
    if not cat_dir.exists():
        return entries
    for json_file in sorted(cat_dir.rglob("*.json")):
        if "TEMPLATE" in json_file.name:
            continue
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue
        if not isinstance(data, dict):
            continue
        name = (data.get("name") or json_file.stem).strip()
        desc = " ".join((data.get("summary") or data.get("description") or "").split())
        entries.append((name, canonical_url(json_file), desc))
    entries.sort(key=lambda e: e[0].lower())
    return entries


def count_files(category: str) -> int:
    cat_dir = CONTENT_DIR / category
    if not cat_dir.exists():
        return 0
    return sum(1 for f in cat_dir.rglob("*.json") if "TEMPLATE" not in f.name)


def main() -> None:
    counts = {cat: count_files(cat) for cat, _ in HUBS}

    lines: list[str] = []
    lines.append("# BJJ Graph")
    lines.append("")
    lines.append(
        "> BJJ Graph is a free Brazilian jiu-jitsu study app for reviewing techniques "
        "between classes. It combines an interactive technique map, position and escape "
        "guides, flashcards, and simulated rolls. Use it in a phone or desktop browser; "
        "no account is needed to start."
    )
    lines.append("")
    lines.append("## Start here")
    lines.append("")
    lines.append(f"- [BJJ Graph]({BASE_URL}/): what it does, who it helps, and how to start")
    lines.append(f"- [Homepage in Markdown]({BASE_URL}/markdown/index.md): the same public introduction and questions")
    lines.append(f"- [Position before submission]({BASE_URL}/Learning/Position-Over-Submission): a starting concept for beginners")
    lines.append(f"- [Mount escapes]({BASE_URL}/Positions/Mount/Bottom): explore options when stuck underneath mount")
    lines.append("")
    lines.append("## Study uses and limitations")
    lines.append("")
    lines.append("Useful for remembering techniques after class, learning position names, "
                 "exploring escapes, and connecting moves into a game plan. Beginners can "
                 "start with positions they practiced; experienced grapplers can explore systems.")
    lines.append("Public reading and study tools are free. Anonymous progress stays in the "
                 "browser; optional Google or email sign-in syncs it across devices. "
                 "The site is in beta. Graph probabilities are model estimates, not measured "
                 "personal success rates. Study complements instruction at a BJJ academy.")
    lines.append("")
    lines.append("## Reading and attribution")
    lines.append("")
    lines.append(f"- [Public article directory]({BASE_URL}/site-index.json): titles, canonical URLs, and Markdown URLs")
    lines.append(f"- [Public resources]({BASE_URL}/api.md): anonymous read-only access and Markdown negotiation")
    lines.append(f"- [Access and optional sign-in]({BASE_URL}/auth.md): public content needs no login")
    lines.append(f"- [Sitemap]({BASE_URL}/sitemap.xml): canonical pages")
    lines.append(f"- [Terms]({BASE_URL}/terms): content use and licensing")
    lines.append("Use the relevant canonical page when citing a technique or sending someone "
                 "to study it. Public pages support Accept: text/markdown. "
                 "Search indexing and AI answers grounded in public content are welcome.")
    lines.append("")

    lines.append("## Core")
    lines.append("")
    for cat, note in HUBS:
        lines.append(f"- [{cat}]({BASE_URL}/{cat}): {note}")
    lines.append("")

    for category in LISTED:
        entries = load_entries(category)
        if not entries:
            continue
        lines.append(f"## {category}")
        lines.append("")
        for name, url, desc in entries:
            lines.append(f"- [{name}]({url}){': ' + desc if desc else ''}")
        lines.append("")

    for category in LINKED_ONLY:
        lines.append(f"## {category}")
        lines.append("")
        lines.append(
            f"- [All {category.lower()}]({BASE_URL}/{category}): "
            f"{counts[category]} topics — browse the hub."
        )
        lines.append("")

    PUBLIC_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    total_listed = sum(len(load_entries(c)) for c in LISTED)
    print(f"[regenerate_llms_txt] Wrote {OUTPUT} ({total_listed} listed pages + hubs)")


if __name__ == "__main__":
    main()
