/**
 * PostHog A/B Testing Event Tracking (Client-Side)
 *
 * Reports A/B testing data to PostHog for analysis:
 * - Reads assignment from cookie (generated by uniform-ab-testing.inline.ts)
 * - Tracks page views, time on page, scroll depth
 * - All data is flat properties for easy PostHog correlation analysis
 *
 * NOTE: This script ONLY reports data, it does NOT generate assignments.
 * Assignment generation happens in uniform-ab-testing.inline.ts (runs in <head>)
 */

declare global {
  interface Window {
    posthog?: {
      capture: (event: string, properties?: Record<string, any>) => void
    }
  }
}

const pageLoadTime = Date.now()

// ============================================================================
// Utility Functions
// ============================================================================

function getCookie(name: string): string | null {
  const value = `; ${document.cookie}`
  const parts = value.split(`; ${name}=`)
  if (parts.length === 2) {
    const cookieValue = parts.pop()?.split(';').shift()
    return cookieValue ? decodeURIComponent(cookieValue) : null
  }
  return null
}

function getPageMetadata() {
  const slug = window.location.pathname
  const contentType = document.body?.dataset?.contentType || 'unknown'
  const sections = JSON.parse(document.body?.dataset?.sections || '[]')

  return {
    slug,
    contentType,
    sectionCount: sections.length,
    sections,
    url: window.location.href
  }
}

function getAssignmentFromCookie(): any | null {
  const cookieValue = getCookie('bjjgraph_ab_assignment')
  if (!cookieValue) return null

  try {
    return JSON.parse(cookieValue)
  } catch {
    return null
  }
}

// ============================================================================
// Event Tracking
// ============================================================================

function trackABPageView(posthog: Window['posthog']): void {
  if (!posthog) return

  const metadata = getPageMetadata()
  const assignment = getAssignmentFromCookie()

  if (!assignment) {
    console.warn('[BJJ Graph AB] No assignment cookie found')
    return
  }

  // Build flat event data
  const eventData: Record<string, any> = {
    ...metadata,
    weekSeed: assignment.weekSeed,
    hiddenCount: assignment.visible.filter((v: boolean) => !v).length,
    enhancedCount: assignment.enhanced.filter((e: boolean) => e).length
  }

  // Add flat properties for each section
  metadata.sections.forEach((sectionId: string, i: number) => {
    eventData[`section_${sectionId}_priority`] = assignment.priorities[i]
    eventData[`section_${sectionId}_visible`] = assignment.visible[i]
    eventData[`section_${sectionId}_enhanced`] = assignment.enhanced[i]
  })

  posthog.capture('ab_page_view', eventData)
}

function trackTimeOnPage(posthog: Window['posthog']): void {
  if (!posthog) return

  const metadata = getPageMetadata()
  const assignment = getAssignmentFromCookie()

  const trackLeave = () => {
    const timeOnPage = Math.round((Date.now() - pageLoadTime) / 1000)

    posthog?.capture('ab_time_on_page', {
      ...metadata,
      time_on_page: timeOnPage,
      weekSeed: assignment?.weekSeed
    })
  }

  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'hidden') trackLeave()
  })

  window.addEventListener('beforeunload', trackLeave)

  document.addEventListener('nav', (e: Event) => {
    const customEvent = e as CustomEvent
    const newUrl = customEvent.detail?.url
    if (newUrl && newUrl !== metadata.slug) trackLeave()
  })
}

function trackScrollDepth(posthog: Window['posthog']): void {
  if (!posthog) return

  const metadata = getPageMetadata()
  const assignment = getAssignmentFromCookie()
  const milestones = [25, 50, 75, 100]
  const reached = new Set<number>()

  const checkScroll = () => {
    const scrollPercentage = Math.round(
      ((window.scrollY + window.innerHeight) / document.documentElement.scrollHeight) * 100
    )

    milestones.forEach(milestone => {
      if (scrollPercentage >= milestone && !reached.has(milestone)) {
        reached.add(milestone)

        posthog?.capture('ab_scroll_depth', {
          ...metadata,
          scroll_depth: milestone,
          weekSeed: assignment?.weekSeed
        })
      }
    })
  }

  let scrollTimeout: number | undefined
  window.addEventListener('scroll', () => {
    if (scrollTimeout) clearTimeout(scrollTimeout)
    scrollTimeout = window.setTimeout(checkScroll, 200) as any
  }, { passive: true })
}

// ============================================================================
// Initialization
// ============================================================================

function waitForPostHog(callback: (posthog: Window['posthog']) => void, maxAttempts = 50): void {
  let attempts = 0

  const checkPostHog = () => {
    attempts++

    if (window.posthog && typeof window.posthog.capture === 'function') {
      callback(window.posthog)
    } else if (attempts < maxAttempts) {
      setTimeout(checkPostHog, 100)
    } else {
      console.warn('[BJJ Graph AB] PostHog not loaded after 5s')
    }
  }

  checkPostHog()
}

function initABTracking(): void {
  // Only track content pages
  const contentType = document.body?.dataset?.contentType
  if (!contentType || !['positions', 'positions-hub', 'transitions', 'submissions', 'principles', 'systems'].includes(contentType)) {
    return
  }

  waitForPostHog((posthog) => {
    trackABPageView(posthog)
    trackTimeOnPage(posthog)
    trackScrollDepth(posthog)
    console.log('[BJJ Graph AB] Tracking initialized')
  })
}

// Start on page load
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initABTracking)
} else {
  initABTracking()
}

// Re-initialize on SPA navigation
document.addEventListener('nav', initABTracking)
